sudo: true
language: node_js

node_js:
  - '6'

skip_cleanup: true

# fail asap when there is a failure
matrix:
  fast_finish: true

# cache node modules
cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - npm i -g webpack
  - npm run build

script: 
  - npm test
  - bash ./deploy.sh
