sudo: true
language: node_js

node_js:
  - '6'

cache:
  yarn: true
  directories:
    - node_modules
    - bower_components

before_install:
  - npm i -g webpack
  - webpack --config webpack.production.config.js --progress --profile --colors

script: 
  - npm test
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; bash ./deploy.sh ; fi
