sudo: false
language: node_js

node_js:
  - '6'

# fail asap when there is a failure
matrix:
  fast_finish: true

# cache node modules
cache:
  directories:
    - node_modules
    - bower_components

before_install:
  # remove useless/non listed deps
  - npm prune
  # faster npm install
  - npm set progress=false
  - npm i -g webpack

script: 
  - npm test
  - bash ./deploy.sh
