language: node_js

node_js:
  - '6'

cache:
  yarn: true
  directories:
    - node_modules
    - bower_components

before_script:
  - npm install -g bower
  - bower install

script:
  - npm prune
  - npm test
  - npm run lint
  - bash ./deploy.sh
